export const ingredientIcons = {
  banana: '/ingredients/banana-svgrepo-com.svg',
  bellPepper: '/ingredients/bell-pepper-vegetable-svgrepo-com.svg',
  salmon: '/ingredients/big-salmon-svgrepo-com.svg',
  broccoli: '/ingredients/broccoli-outline-svgrepo-com.svg',
  carrot: '/ingredients/carrot-organic-svgrepo-com.svg',
  cheese: '/ingredients/cheese-svgrepo-com.svg',
  chickenLeg: '/ingredients/chicken-leg-svgrepo-com.svg',
  corn: '/ingredients/corn-svgrepo-com.svg',
  egg: '/ingredients/egg-svgrepo-com.svg',
  garlic: '/ingredients/garlic-3-svgrepo-com.svg',
  grains: '/ingredients/grains-wheat-svgrepo-com.svg',
  grapes: '/ingredients/grapes-svgrepo-com.svg',
  lemon: '/ingredients/lemon-svgrepo-com.svg',
  lettuce: '/ingredients/lettuce-organic-svgrepo-com.svg',
  milkBottle: '/ingredients/milk-bottle-svgrepo-com.svg',
  mushroom: '/ingredients/mushroom-1-up-videogame-svgrepo-com.svg',
  oilBottle: '/ingredients/oil-bottle-svgrepo-com.svg',
  onion: '/ingredients/onion-svgrepo-com.svg',
  prawn: '/ingredients/prawn-svgrepo-com.svg',
  rice: '/ingredients/rice-svgrepo-com.svg',
  soySauce: '/ingredients/soy-sauce-svgrepo-com.svg',
  spaghetti: '/ingredients/spaghetti-bolognese-svgrepo-com.svg',
  steak: '/ingredients/steak-meat-svgrepo-com.svg',
  strawberry: '/ingredients/strawberry-svgrepo-com.svg',
  tomato: '/ingredients/tomato-svgrepo-com.svg',
  wheat: '/ingredients/wheat-harvest-svgrepo-com.svg',
};

export type IngredientIconName = keyof typeof ingredientIcons;